---
title: "Hurricane Maria Impacts on Stream Quality"
format: html
author: Joshua Cohen, Nicole Pepper, Leilanie Rubinstein, Rachel Swick
execute:
  warning: FALSE
editor_options: 
  chunk_output_type: console
---

## We wanted to investigate the impacts of Hurricane Jeanne (September 13-28, 2004) on stream chemistry data collected from Puerto Rico. We chose to look at water chemistry and discharge at the Rio Espiritu Santo site. 

```{r}
rm(list = ls())
```

### Load packages

```{r}
library(tidyverse)
library(janitor)
library(plyr)
library(lubridate)
library(patchwork)
library(dplyr)
library(plyr)
library(reshape2)
```

### Read in the stream chemistry data for Rio Espiritu

```{r}
# read in and clean data
# change all NAs to be stored in data frame the same way
# use clean names to normalize column naming conventions to lower_snake_case
# filter for date range - Hurricane Jeanne occurred on September 13-28, 2004 and we are querying for data +/- a month

RES <- read_csv(file.path("/courses/EDS214/group_project/2024/dream_stream_team/raw_data", "RioEspirituSanto.csv"), na = "-9999") %>% 
  clean_names() %>% 
  dplyr::rename(date = sample_date) %>%
  dplyr::filter(date >= "2004-08-13" & date <= "2004-10-28")

```

### Load USGS API 

```{r}
library(dataRetrieval)
```

```{r}
# Set parameters for this query
# Site 50063800 - Rio Espiritu Santo NR Rio Grande, PR

siteNumber <- "50063800"
parameterCd <- "00060" # Discharge
startDate <- "2004-08-13" 
endDate <- "2004-10-28"
```

```{r}
# Query the API for site discharge
# clean variable names
discharge_espiritu <- readNWISdv(siteNumber, parameterCd, startDate, endDate) %>% 
  dplyr::rename(date = Date) %>% 
  dplyr::rename(discharge_ft3_s = X_00060_00003)
```

```{r}
# combine both data frames (discharge_espiritu, RES) using `full_join()`
combined_data <- full_join(discharge_espiritu, RES, by = 'date')
```

```{r}
# filter date to desired range
# select columns

chem_discharge_data <- combined_data %>% 
  select(date, discharge_ft3_s, cond, k, no3_n, doc) %>% 
  dplyr::filter(date >= "2004-08-30" & date <= "2004-10-12") %>% 
  mutate(cond = as.numeric(cond),
         k = as.numeric(k),
         no3_n = as.numeric(no3_n),
         doc = as.numeric(doc))
```


```{r}
# tidy the combined chemistry to ready it for plotting
# chem_discharge_long <- chem_discharge_data %>% 
#   select(date, discharge_ft3_s, cond, k, no3_n, doc) %>%
#   tidyr::pivot_longer(discharge_ft3_s:doc, names_to = "variable", values_to = "value")
```

```{r}

# ggplot(data = chem_discharge_data) +
#     geom_line(aes(x = date, y = k)) +
#     geom_line(aes(x = date, y = discharge_ft3_s)) +
#     scale_y_continuous(name = "Potassium",
#                        sec.axis = sec_axis(discharge_ft3_s, name = "Discharge cu ft/s"))

```


```{r}
# i was testing multiple ways to ready the data to be faceted
# i decided to use the pivot method since apparently melt is deprecated

qrd_pivot <- quality_rainfall_data %>% 
  select(date, discharge_ft3_s, p_h, cond, po4_p, doc) %>%
  pivot_longer(discharge_ft3_s:doc, names_to = "variable", values_to = "value")
```

```{r}
# this is the graph we'll use
# im kinda just guessing the units here, hopefully ill figure them out later

# labeller argument is weird but i guess it kind of works like this
el_label <- c(`cond` = "Conductivity (S/m)",
              `discharge_ft3_s` = "Discharge (ft^3/s)",
              `doc` = "Dissolved Organic Carbon (ppb??)",
              `p_h` = "pH",
              `po4_p` = "PO4-P (mg/L)")


ggplot(data = subset(qrd_pivot, !is.na(value)), 
       aes(y = value, x = date, color = variable)) + 
  geom_point(size = 4, show.legend = FALSE) + 
  facet_wrap(vars(variable), strip.position = "bottom", labeller = as_labeller(el_label)) + 
  scale_x_date(position = "top") + 
  xlab("Date")
```
















